modify install LLVM step to check if LLVM coverage is installed

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,10 +64,14 @@ runs:
         echo "GCOVR_ARGS=$ARGS" >> $GITHUB_ENV
         echo "COVERALLS_OUT=$COVERALLS_OUT" >> $GITHUB_ENV
 
-    - name: Install LLVM
+    - name: Check if LLVM coverage is installed
       if: contains(inputs.gcov-executable, 'llvm-cov')
       shell: bash
-      run: sudo apt install -y llvm
+      run: |
+        if ! command -v llvm-cov &> /dev/null; then
+          echo "llvm-cov could not be found, installing..."
+          sudo apt install -y llvm
+        fi
 
     - name: Generate code coverage report using gcovr
       shell: bash
