try to install gcovr if could not be found

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,4 +8,9 @@ runs:
   using: composite
   steps:
     - shell: bash
-      run: echo 'test'
+      run: |
+        if ! command -v gcovr &> /dev/null; then
+          echo "gcovr could not be found, installing..."
+          pip install gcovr
+        fi
+        gcovr --version
